### ISSUE TITLE
Band power per second

### ISSUE THREAD

**Issue by GiddeonWyeth** [pwstegman/bci.js#7]
Hello Pierce!
My name is Anton and I’m using your js package called BCI.js but I can’t understand one thing and I believe you can help me :)
I have an array of signals  from EEG session which lasted for 30 seconds and I want to get average alpha band power for every second.
I divide my signals by 30 and on each subarray I’m using signalBandPower method. Is this correct or I’m doing something wrong?

Thank you in advance!

**Comment by pwstegman** [comment]
Hi Anton! Yes, that's the right idea. For averaged band power values, you can use the method [bci.averageBandPowers](https://bci.js.org/docs/module-bcijs.html#.averageBandPowers) to average all the channel band power values together.

Here's an example on how I would epoch data and grab band power values averaged over every channel:

```javascript
const bci = require('bcijs');

/*
Each row of data should be a sample, and each column in each row should be a channel.
In this example, there are 3 samples taken from 2 electrodes.
*/
let data = [
  [1, 2],
  [3, 1],
  [4, 2],
  // ...
];

/*
If your data is the transpose (an array where each row is a channel and each column is a sample),
you can use the following line to transpose it to the proper format:
data = bci.transpose(data);
*/

// Let's say the sample rate is 256 Hz
let sample_rate = 256;

// Now we can get an array of band powers
let alphas = bci.windowApply(
    data,
    epoch => bci.averageBandPowers(epoch, sample_rate, ['alpha']),
    sample_rate, // every epoch should be sample_rate long (1 second)
    sample_rate // each epoch should step forward sample_rate samples (no overlap between epochs)
);

console.log(alphas);
/*
[
  [ 3.2 ],
  [ 2.3 ],
  [ 5.2 ],
]
*/
```

The reason the result is an array of arrays is because you can compute multiple band power values at once. For example, you could change the averageBandPowers method to read:

```javascript
bci.averageBandPowers(epoch, sample_rate, ['alpha', 'beta', 'theta'])
```

To get alpha, beta, and theta values in each output row

If you want to get just a 1D array of the alphas, you could transpose and grab the first row:

```javascript
alphas = bci.transpose(alphas)[0];
// [3.2, 2.3, 5.2]
```
